require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 30

Metrics/AbcSize:
  Max: 100

Metrics/ClassLength:
  Max: 500

Layout/LineLength:
  Max: 170

Metrics/ModuleLength:
  Max: 300

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Metrics/BlockLength:
  Max: 30
